import streamlit as st


def app():
    st.title('Welcome to Read Me')
    st.subheader('Introduction of the website')
    st.text('The website allows us to select two different methods via the Radio selection')
    st.text('Button.')
    st.text('1.	Classification of Image')
    st.text('2.	Anomaly Detection')
    st.text('Upon selecting Classification of Image, it will display a visualization ')
    st.text('showing if it is close to 1 (Anomaly) or 0 (Normal), after submitting')
    st.text('an unknown image.Whereas the Anomaly Detection approach shows whether ')
    st.text('the image is anomaly or not by drawing a histogram of SSIM scores and ')
    st.text('showing where the score is located. The visualizations are shown using')
    st.text('Matplotlib. Some sample images are given in the code folder to test the app')
    st.subheader('Navigation:')
    st.text('There are four Navigation section on the side bar of the website. ')
    st.text('1.	Home: The Home page consists of the Anomaly detection and classification')
    st.text('   methods ')
    st.text('2.	About: This page contains the Video presentation from the team')
    st.text('3.	Members: This page consists of the information about the team members')
    st.subheader('REST API')
    st.text('1.	/model/classification: The POST HTTP Route to upload the image and ')
    st.text('obtain the classification-based visualization, along with a text containing')
    st.text(' image label and the input image')
    st.text('2.	/model/anomaly_detection: The POST HTTP Route to upload the image and')
    st.text('obtain the anomaly detection based visualization, along with a text containing')
    st.text('image label and its output reconstructed image')
